### ISSUE TITLE
Failed to load passes from 'bpfcov/build/lib/libBPFCov.so'

### ISSUE THREAD

**Issue by liusy58** [elastic/bpfcov#3]
Hi, sir, I encounter the error shown below after I run the command `make cov` in example/src directory.

```
bpfcov/build/lib/libBPFCov.so'
```

**Comment by leodido** [comment]
As discussed privately, this is solved now.

The problem was using a `bpftool` without the skeletons feature. In fact, bpfcov requires a bpftool with skeletons feature on to work (see [this line](https://github.com/elastic/bpfcov/blob/f06a65b84477dfebc9cff58ae4e4662beed4c411/examples/src/Makefile#L70)).

**Comment by leodido** [comment]
I cannot close the issue because I don't have any more permissions to admin this repo ...

Some at @elastic would help and give me permissions on this repo? Maybe @ferullo?
